### ISSUE TITLE
CLARA 2E - No bluetooth connection

### ISSUE THREAD

**Issue by F5OEO** [ubx/XCSoarData#1]
Thanks for the scripts ! 

I modified connect-gns-2000 with the ethernet address of my ble device (softrf).
I launch this script prior to launch xcsoar.
In config , I can see rfcom0 but there is no data...

Hope that I use the correct procedure.
Maybe there is an issue with the channel number ? 
Any suggestion to debug ?

**Comment by ubx** [comment]
Have you switched off Wi-Fi?"

**Comment by ubx** [comment]
To test if the GNS 2000 is visible, you can do the following:

-  Start Nickel.
-  Settings
-  Enable Bluetooth connection.
-  Turn on Bluetooth.
-  In available devices, you should see the GNS 2000.

**Comment by ubx** [comment]
Most likely a pairing Bluetooth device problem, see f239379f28b229117979194e0accb8952b1426dd

**Comment by F5OEO** [comment]
Thanks for remarks , in more details : 
- Wifi is not on (I use ip over usb to debug)
- device is paired and connected
- device is also trusted
- rfcomm state is "clean" after rfcomm bind

As soon as I try with xcsoar or with cat /dev/rfcom0 , rfcom state becomes "close".
I suspect that a client which close the rfcom connection close at the sammme time the bluetooth connection 

I wonder why use /sbin/hciattach -n ttymxc1 any **1500000** flow -t 20 , I try with 115200 but the bluetooth connection is not possible

**Comment by F5OEO** [comment]
Here is the latest debug..
```
`/mnt/onboard/XCSoarData/kobo/scripts # bluetoothctl info
Device EA:CB:7A:0B:39:5D (random)
        Name: SoftRF-a39204-LE
        Alias: SoftRF-a39204-LE
        Paired: yes
        Trusted: yes
        Blocked: no
        Connected: yes
        LegacyPairing: no
        UUID: Vendor specific           (00001530-1212-efde-1523-785feabcd123)
        UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
        UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
        UUID: Device Information        (0000180a-0000-1000-8000-00805f9b34fb)
        UUID: Battery Service           (0000180f-0000-1000-8000-00805f9b34fb)
        UUID: Unknown                   (0000ffe0-0000-1000-8000-00805f9b34fb)
        UUID: Vendor specific           (03b80e5a-ede8-4b33-a751-6ce34ec4c700)
        UUID: Nordic UART Service       (6e400001-b5a3-f393-e0a9-e50e24dcca9e)
        UUID: Vendor specific           (aba27100-143b-4b81-a444-edcd0000f020)
        Battery Percentage: 0x41 (65)
/mnt/onboard/XCSoarData/kobo/scripts # rfcomm connect 0 EA:CB:7A:0B:39:5D
Can't connect RFCOMM socket: Host is down
`
```

**Comment by ubx** [comment]
Here is the output from my GNS 2000 after running the Connect-GNS-2000 script:
```
/mnt/onboard/XCSoarData/kobo/scripts # bluetoothctl info 5C:B6:CC:00:3F:A1
Device 5C:B6:CC:00:3F:A1 (public)
        Name: GNS 2000
        Alias: GNS 2000
        Class: 0x00240400
        Icon: audio-card
        Paired: yes
        Trusted: yes
        Blocked: no
        Connected: no
        LegacyPairing: no
        UUID: Vendor specific           (00000000-deca-fade-deca-deafdecacaff)
        UUID: Serial Port               (00001101-0000-1000-8000-00805f9b34fb)
        UUID: PnP Information           (00001200-0000-1000-8000-00805f9b34fb)
        Modalias: usb:v0A12p0001d0001
/mnt/onboard/XCSoarData/kobo/scripts # 

/mnt/onboard/XCSoarData/kobo/scripts # cat /dev/rfcomm0 
$GPGGA,143340.394,,,,,0,0,,,M,,M,,*47
...
...
```
It appears that your device doesn't have a Serial Port. Also, I don't have a SoftRF Badge Edition device to test it.

**Comment by F5OEO** [comment]
"It appears that your device doesn't have a Serial Port. Also, I don't have a SoftRF Badge Edition device to test it."
Yes, this is probably the issue : it works with xcsoar on android as the android version is based on the nordic library wich is also the case on the softrf device. I think that I have probably to use this library on the kobo.

**Comment by ubx** [comment]
In the meantime, I got a SoftRF Prime Edition MkIII device. Tests on my Libra 2 show that it would be possible to receive data. Test on a remote Kobo terminal:
```
bluetoothctl
connect F4:12:FA:67:E9:C5
menu gatt
select-attribute 0000ffe1-0000-1000-8000-00805f9b34fb
notify on

[SoftRF-67e9c4-LE:/service0028/char0029]#                   24 47 4e 47 47 41 2c 31 31 33 39 32 38 2e 30 30  $GNGGA,113928.00
[SoftRF-67e9c4-LE:/service0028/char0029]#                   2c 2c 2c 2c
...
...

```
It should be possible to write a small C program (similar to https://github.com/Jakeler/ble-serial) that receives data and sends it to a serial port (`/dev/ttyxx`).

or

In XCSoar, implement a Bluetooth port for Linux, similar to the `HM10Port.java` for Android.

**Comment by ketan** [comment]
I'm trying to pair a xctracer mini iv GPS. It contains the following characteristics/services as reported by bluetoothctl.

```[NEW] Primary Service (Handle 0x0000)
        /org/bluez/hci0/dev_DD_9F_C9_96_53_92/service000a
        00001801-0000-1000-8000-00805f9b34fb
        Generic Attribute Profile
[NEW] Primary Service (Handle 0x0000)
        /org/bluez/hci0/dev_DD_9F_C9_96_53_92/service000b
        0000ffe0-0000-1000-8000-00805f9b34fb
        Unknown
[NEW] Characteristic (Handle 0x0000)
        /org/bluez/hci0/dev_DD_9F_C9_96_53_92/service000b/char000c
        0000ffe1-0000-1000-8000-00805f9b34fb
        Unknown
[NEW] Descriptor (Handle 0x0000)
        /org/bluez/hci0/dev_DD_9F_C9_96_53_92/service000b/char000c/desc000e
        00002902-0000-1000-8000-00805f9b34fb
        Client Characteristic Configuration
[NEW] Descriptor (Handle 0x0000)
        /org/bluez/hci0/dev_DD_9F_C9_96_53_92/service000b/char000c/desc000f
        00002901-0000-1000-8000-00805f9b34fb
        Characteristic User Description
```

`0000ffe1-0000-1000-8000-00805f9b34fb` is the characteristic I'm interested in - that contains the NMEA sentences as reported by xctracer. I've tried a bunch of options and failed (miserably, might I add). Has anyone achieved pairing this vario (or something similar) that I can look at?

Thanks

**Comment by ubx** [comment]
According to the description, the XC Tracer Mini IV device has a BLE Module. However, BLE is not supported in the Kobo-XCSoar (and other Unix) version. As mentioned in [my comment](https://github.com/ubx/XCSoar_Scripts/issues/1#issuecomment-1858809634), someone has to implement it in XCSoar or write a program that receives data and sends it to a serial port. You could create a feature request [here](https://github.com/XCSoar/XCSoar/issues/new/choose).
